export const api_properties = {
  API_LOGIN: "/api/v1/user/login/email",
  API_REGISTER: "/api/v1/user/email",
  API_ADD_ROLES: "/api/v1/user/role",
  API_GET_USER_ROLES: "/api/v1/user/roles",
  API_GET_USER_PERSONAL_DETAILS: "/api/v1/users/personal_details/gts_user_id/",
  API_GET_RECOMMENDED_SERVICES: "/api/v1/gts_user_recommended_job/gts_user_id/",
  API_GET_ACTIVE_SKILLS: "/api/v1/skills/active",
  API_GET_ACTIVE_COMPANIES: "/api/v1/company/active",
  API_GET_ACTIVE_SERVICE_TITLES: "/api/v1/job/title/active",
  API_GET_ACTIVE_COUNTRIES: "/api/v1/countries/active",
  API_GET_ACTIVE_DEGREES: "/api/v1/degree/active",
  API_GET_ACTIVE_CITIES: "/api/v1/city/active",
  API_GET_ACTIVE_INSTITUTES: "/api/v1/institute/active",
  API_GET_LANGUAGES_ACTIVE: "/api/v1/languages/active",
  API_GET_ACTIVE_CURRENCIES: "/api/v1/currencies/active",
  API_GET_CITIES_BY_COUNTRY: "/api/v1/city/country_id/",
  API_POST_SERVICE_APPLICATIONS: "/api/v1/job/applications",
  API_GET_SERVICE_APPLICATIONS_BY_APPLIED_ID:
    "/api/v1/job/applications/applied_job_id/",
  API_GET_SERVICE_APPLICATIONS_BY_APPLICANT_ID:
    "/api/v1/job/applications/applicant_id/",
  API_GET_SC_SERVICES_ACTIVE: "/api/v1/employer/job_post/active/employer_id/",
  API_SC_SERVICES: "/api/v1/employer/job_post",
  API_GET_ACTIVE_INDUSTRIES: "/api/v1/industry/active",
  API_SEARCH_SERVICES: "/api/v1/gts_job_search",
  API_GET_USER_SALARY: "/api/v1/user/salary/user_id/",
  API_USER_SALARY: "/api/v1/user/salary",
  API_EMPLOYMENT_AGREEMENT: "/api/v1/employment/agreements",
  API_GET_EMPLOYMENT_AGREEMENT:
    "/api/v1/employment/agreements/employment_agreement_id/",
  API_USER_SIGNATURE: "/api/v1/user/signature/user_id/",
  API_LOGIN: "/api/v1/user/login/email",
  API_REGISTER: "/api/v1/user/email",
  API_ADD_ROLES: "/api/v1/user/role",
  API_GET_USER_ROLES: "/api/v1/user/roles",
  API_GET_ACTIVE_USER: "/api/v1/user/active",
  API_GET_USER_PERSONAL_DETAILS: "/api/v1/users/personal_details/gts_user_id/",
  API_GET_RECOMMENDED_SERVICES: "/api/v1/gts_user_recommended_job/gts_user_id/",
  API_GET_ACTIVE_JOB_TITLES: "/api/v1/job/title/active",
  API_GET_ACTIVE_INDUSTRIES: "/api/v1/industry/active",
  API_GET_SC_COMPANY_DETAILS: "/api/v1/employer_company_detail/employer_id/",
  API_GET_ACTIVE_CURRENCIES: "/api/v1/currencies/active",
  API_GET_ACTIVE_SKILLS: "/api/v1/skills/active",
  API_GET_ACTIVE_COMPANIES: "/api/v1/company/active",
  API_GET_ACTIVE_SERVICE_TITLES: "/api/v1/job/title/active",
  API_GET_ACTIVE_COUNTRIES: "/api/v1/countries/active",
  API_GET_ACTIVE_DEGREES: "/api/v1/degree/active",
  API_GET_ACTIVE_CITIES: "/api/v1/city/active",
  API_GET_ACTIVE_STATES: "/api/v1/states/active",
  API_GET_ACTIVE_TRAINING: "/api/v1/trainings/active",
  API_GET_CITIES_BY_COUNTRY: "/api/v1/city/country_id/",
  API_GET_CITIES_BY_STATE: "/api/v1/city/state_id/",
  API_GET_STATES_BY_COUNTRY: "/api/v1/states/country_id/",
  API_GET_ACTIVE_INSTITUTES: "/api/v1/institute/active",
  API_GET_LANGUAGES_ACTIVE: "/api/v1/languages/active",
  API_GET_TIMEZONES_ACTIVE: "/api/v1/timezone/active",
  API_SEARCH_SERVICE_PROVIDER: "/api/v1/search_service_provider",
  API_SEARCH_TRAINING: "/api/v1/search_training",
  API_USER_TRAINING: "/api/v1/users/trainings",
  API_GET_USER_TRAINING: "/api/v1/users/trainings/trainee_id/",
  API_GET_TRAINING_CENTER: "/api/v1/training_center/active",
  API_GET_RECOMMENDED_TRAINING_BY_USER_ID:
    "/api/v1/gts_user_recommended_trainings/gts_user_id/",
  API_TRAINING_WISH: "/api/v1/trainings/wishes",
  API_SCHEDULE_INTERVIEW: "/api/v1/gts_interview_schedule",
  API_CANDIDATE_AGREEMENT: "/api/v1/candidate/agreements",
  API_GET_CANDIDATE_AGREEMENT: "/api/v1/candidate/agreements/employer_id/",
};
