export const endpoints_properties =
  {
    "ENDPOINT_IDENTITY_LOCAL" : "http://localhost:4728",
    "ENDPOINT_PERSONAL_DETAILS_LOCAL" : "http://localhost:4753",
    "ENDPOINT_RECOMMENDED_SERVICES_LOCAL" : "http://localhost:4755",
    "ENDPOINT_SKILLS_LOCAL" : "http://localhost:4744",
    "ENDPOINT_SERVICE_APPLICATIONS_LOCAL" : "http://localhost:4740",
    "ENDPOINT_SC_SERVICES_LOCAL": "http://localhost:4726",
    "ENDPOINT_SERVICE_TITLES_LOCAL" : "http://localhost:4727",
    "ENDPOINT_COUNTRIES_LOCAL":"http://localhost:4711",
    "ENDPOINT_CITIES_LOCAL":"http://localhost:4706",
    "ENDPOINT_DEGREES_LOCAL" : "http://localhost:4702",
    "ENDPOINT_INSTITUTES_LOCAL": "http://localhost:4721",
    "ENDPOINT_LANGUAGES_LOCAL" :"http://localhost:4729",
    "ENDPOINT_CURRENCIES_LOCAL" : "http://localhost:4767",
    "ENDPOINT_USER_SALARY_LOCAL" : "http://localhost:4766",
    "ENDPOINT_SEARCH_SERVICES_LOCAL" : "http://localhost:4739",
    "ENDPOINT_EMPLOYMENT_AGREEMENT_LOCAL" : "http://localhost:4714",
    "ENDPOINT_PERSONAL_DETAILS_LOCAL" : "http://localhost:4753",
    "ENDPOINT_SKILLS_LOCAL" : "http://localhost:4744",
    "ENDPOINT_JOB_TITLES_LOCAL" : "http://localhost:4727",
    "ENDPOINT_SC_COMPANY_DETAILS_LOCAL" : "http://localhost:4712",
    "ENDPOINT_INDUSTRIES_LOCAL" :"http://localhost:4719",
    "ENDPOINT_COMPANIES_LOCAL" : "http://localhost:4707",
    "ENDPOINT_CITIES_LOCAL":"http://localhost:4706",
    "ENDPOINT_CURRENCIES_LOCAL" : "http://localhost:4767",
    "ENDPOINT_TIMEZONES_LOCAL" : "http://localhost:4703",
    "ENDPOINT_DEGREES_LOCAL" : "http://localhost:4702",
    "ENDPOINT_INSTITUTES_LOCAL": "http://localhost:4721",
    "ENDPOINT_LANGUAGES_LOCAL" :"http://localhost:4729",
    "ENDPOINT_SEARCH_SERVICE_PROVIDER_LOCAL" : "http://localhost:4738",
    "ENDPOINT_SEARCH_TRAINING_LOCAL" : "http://localhost:4768",
    "ENDPOINT_USER_TRAINING_LOCAL": "http://localhost:4750",
    "ENDPOINT_TRAINING_WISH_LOCAL": "http://localhost:4724",
    "ENDPOINT_COUNTRIES_LOCAL":"http://localhost:4711",
    "ENDPOINT_STATES_LOCAL" : "http://localhost:4745",
    "ENDPOINT_TRAINING_LOCAL" : "http://localhost:4754",
    "ENDPOINT_TRAINING_CENTRE_LOCAL" : "http://localhost:4731",
    "ENDPOINT_INTERVIEW_SCHEDULAR_LOCAL" : "http://localhost:4722",
    "ENDPOINT_RECOMMENDED_TRAINING_LOCAL" : "http://localhost:4756",
    "ENDPOINT_CANDIDATE_AGREEMENT_LOCAL" : "http://localhost:4704",
    "ENDPOINT_USER_SIGNATURE_LOCAL" : "http://localhost:4742",
    "ENDPOINT_DEV" : "https://rk5r6o4uo8.execute-api.ap-south-1.amazonaws.com/dev", 
    // "ENDPOINT_STAGE" : "https://o3xznf3iy6.execute-api.ap-south-1.amazonaws.com/stage",
    // "ENDPOINT_PROD" :  "https://o3xznf3iy6.execute-api.ap-south-1.amazonaws.com/prod",
  }